name: 'Auto-publish NPM Package'

on:
  push:
    branches:
      - '**'
#      - main

jobs:
  push_to_registry:
    name: 'Setup, and publish'
    runs-on: ubuntu-latest

    steps:
      - name: 'Check out the repo'
        uses: actions/checkout@v4

      - name: 'Set up Node'
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'

      - name: 'Install dependencies, build and publish'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: | 
          npm ci
          npm run build
          npm publish
