name: 'Auto-publish NPM Package'

on:
  push:
    branches:
      - '**'
#      - main

jobs:
  push_to_registry:
    name: 'Setup, and publish'
    runs-on: ubuntu-latest

    steps:
      - name: 'Check out the repo'
        uses: actions/checkout@v4

      - name: 'Set up Node'
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'

      - name: 'Dependencies and tests'
        run: |
          npm ci
          npm test

      - name: 'Install dependencies, build and publish'
        uses: JS-DevTools/npm-publish@v3
        with:
          token: ${{ secrets.NPM_TOKEN }}
