name: 'NPM Version Check'

on: pull_request

jobs:
  push_to_registry:
    name: 'NPM Version Check'
    runs-on: ubuntu-latest

    steps:
      - name: 'Check out the repo'
        uses: actions/checkout@v4

      - name: 'Set up Node'
        uses: actions/setup-node@v4
        with:
          registry-url: 'https://registry.npmjs.org'
          node-version: 'lts/*'
          check-latest: true

      - name: 'Check if version is published'
        run: |
          package_version=$(npm pkg get version --workspaces=false | tr -d \")
          npm_versions=$(npm view @ucp-npm/components versions)
          compare=$package_version
          # Convert JSON array to string
          versions=$(echo "$npm_versions" | tr -d '\n' | tr -d ' ' | tr -d '"')
          
          # Check if compare is present in JSON array
          if [[ $versions == *"$compare"* ]]; then
            # Check if the compare is an exact match
            if [[ $versions == *"$compare""']"* || $versions == *"$compare""',"* ]]; then
              echo "version_found=true" >> $GITHUB_ENV
              echo "=========================================================================="
              echo "Version $compare is already published."
              echo "Please update 'version' in package.json. Good to go."
              echo "=========================================================================="
              echo "::error::Version $compare is already published."
              exit 1
            else
              echo "version_found=false" >> $GITHUB_ENV
              echo "Version $compare not found in NPM"
            fi
          else
            echo "version_found=false" >> $GITHUB_ENV
            echo "Version $compare not found in NPM"
          fi
